/** Central limits for recommendation volume — tune here to show more/fewer titles. */
export const RECOMMENDATION_LIMITS = {
  SECTION_BEST_MATCHES: 24,
  SECTION_MUST_WATCH: 20,
  SECTION_BECAUSE_LOVED: 16,
  SECTION_HIDDEN_GEMS: 20,
  SECTION_EXPLORE: 20,
  SECTION_MORE_PICKS: 30,
  SEED_MOVIES_FOR_BECAUSE: 4,
  FILTERED_RESULTS: 60,
  FILTERED_TMDB_PAGES: 10,
  DIVERSIFY_MAX_PER_GENRE: 8,
  DIVERSIFY_MAX_PER_DECADE: 12,
} as const;

export const DEFAULT_PRIMARY_LANGUAGES = ["en", "ta", "hi", "te", "ml", "kn"] as const;

export const RETRIEVAL_LIMITS = {
  ITEM_REC_PER_PAGE: 20,
  ITEM_REC_PAGES: 2,
  GENRE_DISCOVER_PAGES: 2,
  GENRE_DISCOVER_PER_PAGE: 20,
  HIDDEN_GEM_PER_PAGE: 20,
  TOP_RATED_PAGES: 5,
  TRENDING_PER_PAGE: 20,
  DECADE_ESSENTIAL_PER_PAGE: 15,
  EXPLORE_PER_PAGE: 20,
  COLD_START_DECADE_COUNT: 8,
  COLD_START_GENRE_DISCOVER: 20,
  COLD_START_TOP_RATED: 20,
} as const;
